# Generated by Django 5.2.6 on 2025-09-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSP',
            fields=[
                ('MaLoaiSP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenLoaiSP', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Loại sản phẩm',
                'verbose_name_plural': 'Loại sản phẩm',
                'db_table': 'LoaiSP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('MaNCC', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenNCC', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('DienThoai', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'db_table': 'NhaCungCap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenNV', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('DienThoai', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách nhân viên',
                'db_table': 'NhanVien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=255)),
                ('CPU', models.CharField(blank=True, max_length=100, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('OCung', models.CharField(blank=True, max_length=50, null=True)),
                ('CardManHinh', models.CharField(blank=True, max_length=100, null=True)),
                ('GiaNhap', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('Thue', models.IntegerField(blank=True, null=True)),
                ('GiaBan', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('SoLuongTon', models.IntegerField(blank=True, null=True)),
                ('HinhAnh', models.CharField(blank=True, max_length=255, null=True)),
                ('LaiGop', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'SanPham',
                'managed': False,
            },
        ),
    ]
