# Generated by Django 5.2.6 on 2025-09-16 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSP',
            fields=[
                ('MaLoaiSP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenLoaiSP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('MaNCC', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenNCC', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('DienThoai', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=255)),
                ('CPU', models.CharField(blank=True, max_length=100, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('OCung', models.CharField(blank=True, max_length=50, null=True)),
                ('CardManHinh', models.CharField(blank=True, max_length=100, null=True)),
                ('GiaBan', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('SoLuongTon', models.IntegerField(blank=True, null=True)),
                ('HinhAnh', models.CharField(blank=True, max_length=255, null=True)),
                ('MaLoaiSP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SanPham.loaisp')),
                ('MaNCC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SanPham.nhacungcap')),
            ],
        ),
    ]
