# Generated by Django 5.2.6 on 2025-09-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSP',
            fields=[
                ('MaLoaiSP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenLoaiSP', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Loại sản phẩm',
                'verbose_name_plural': 'Loại sản phẩm',
                'db_table': 'LoaiSP',
            },
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('MaNCC', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenNCC', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('DienThoai', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'db_table': 'NhaCungCap',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenNV', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('DienThoai', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách nhân viên',
                'db_table': 'NhanVien',
            },
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('MaPN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NgayNhap', models.DateTimeField(auto_now_add=True)),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=18)),
                ('MaNCC', models.ForeignKey(db_column='MaNCC', on_delete=django.db.models.deletion.CASCADE, to='SanPham.nhacungcap')),
                ('MaNV', models.ForeignKey(db_column='MaNV', on_delete=django.db.models.deletion.CASCADE, to='SanPham.nhanvien')),
            ],
            options={
                'db_table': 'PhieuNhap',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=255)),
                ('CPU', models.CharField(blank=True, max_length=100, null=True)),
                ('RAM', models.CharField(blank=True, max_length=50, null=True)),
                ('OCung', models.CharField(blank=True, max_length=50, null=True)),
                ('CardManHinh', models.CharField(blank=True, max_length=100, null=True)),
                ('GiaNhap', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('Thue', models.IntegerField(blank=True, null=True)),
                ('GiaBan', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('SoLuongTon', models.IntegerField(blank=True, null=True)),
                ('HinhAnh', models.CharField(blank=True, max_length=255, null=True)),
                ('LaiGop', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('MaLoaiSP', models.ForeignKey(db_column='MaLoaiSP', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SanPham.loaisp')),
                ('MaNCC', models.ForeignKey(db_column='MaNCC', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SanPham.nhacungcap')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'SanPham',
            },
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('MaCTPN', models.AutoField(db_column='MaCTPN', primary_key=True, serialize=False)),
                ('SoLuong', models.PositiveIntegerField()),
                ('GiaNhap', models.DecimalField(decimal_places=2, max_digits=18)),
                ('MaPN', models.ForeignKey(db_column='MaPN', on_delete=django.db.models.deletion.CASCADE, to='SanPham.phieunhap')),
                ('MaSP', models.ForeignKey(db_column='MaSP', on_delete=django.db.models.deletion.CASCADE, to='SanPham.sanpham')),
            ],
            options={
                'db_table': 'ChiTietPhieuNhap',
                'unique_together': {('MaPN', 'MaSP')},
            },
        ),
    ]
