# Generated by Django 5.2.6 on 2025-09-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SanPham', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaisp',
            options={'verbose_name': 'Loại sản phẩm', 'verbose_name_plural': 'Loại sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='nhacungcap',
            options={'verbose_name': 'Nhà cung cấp', 'verbose_name_plural': 'Nhà cung cấp'},
        ),
        migrations.AlterModelOptions(
            name='sanpham',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
    ]
