# Generated by Django 5.2.6 on 2025-09-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenKH', models.CharField(max_length=255)),
                ('DienThoai', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.CharField(blank=True, max_length=255, null=True)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Danh sách khách hàng',
                'db_table': 'KhachHang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenNV', models.CharField(max_length=255)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
                ('DienThoai', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Danh sách nhân viên',
                'db_table': 'NhanVien',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quyen',
            fields=[
                ('MaQuyen', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TenQuyen', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Quyền',
                'verbose_name_plural': 'Quyền',
                'db_table': 'Quyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('MaTK', models.CharField(max_length=20, unique=True)),
                ('TenDangNhap', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': 'Danh sách tài khoản',
                'db_table': 'TaiKhoan',
                'managed': False,
            },
        ),
    ]
