# Generated by Django 5.2.6 on 2025-09-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('MaCTDH', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField()),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name': 'Chi Tiết Đơn Hàng',
                'verbose_name_plural': 'Chi Tiết Đơn Hàng',
                'db_table': 'ChiTietDonHang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDH', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('MaKH', models.CharField(blank=True, max_length=20, null=True)),
                ('MaNV', models.CharField(max_length=20)),
                ('NgayLap', models.DateTimeField(auto_now_add=True)),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TrangThai', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Đơn Hàng',
                'verbose_name_plural': 'Đơn Hàng',
                'db_table': 'DonHang',
                'managed': False,
            },
        ),
    ]
