# Generated by Django 5.2.6 on 2025-09-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('MaCTPN', models.AutoField(db_column='MaCTPN', primary_key=True, serialize=False)),
                ('SoLuong', models.PositiveIntegerField()),
                ('GiaNhap', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name': 'Chi Tiết Phiếu Nhập',
                'verbose_name_plural': 'Chi Tiết Phiếu Nhập',
                'db_table': 'ChiTietPhieuNhap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('MaPN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NgayNhap', models.DateTimeField(auto_now_add=True)),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name': 'Phiếu Nhập',
                'verbose_name_plural': 'Phiếu Nhập',
                'db_table': 'PhieuNhap',
                'managed': False,
            },
        ),
    ]
